name: React CI/CD

on:
  push:
    branches:
      - ci/cd-main
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      REACT_APP_S3_ACCESS_KEY_ID: ${{ secrets.REACT_APP_S3_ACCESS_KEY_ID }}
      REACT_APP_S3_SECRET_ACCESS_KEY: ${{ secrets.REACT_APP_S3_SECRET_ACCESS_KEY }}
      REACT_APP_S3_REGION: ${{ secrets.REACT_APP_S3_REGION }}
      REACT_APP_S3_BUCKET: ${{ secrets.REACT_APP_S3_BUCKET }}
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DATABASE_HOST: ${{secrets.DATABASE_HOST}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - name: Create .env File
        run: |
          echo "REACT_APP_S3_ACCESS_KEY_ID=${{ secrets.REACT_APP_S3_ACCESS_KEY_ID }}" > .env
          echo "REACT_APP_S3_SECRET_ACCESS_KEY=${{ secrets.REACT_APP_S3_SECRET_ACCESS_KEY }}" >> .env
          echo "REACT_APP_S3_REGION=${{ secrets.REACT_APP_S3_REGION }}" >> .env
          echo "REACT_APP_S3_BUCKET=${{ secrets.REACT_APP_S3_BUCKET }}" >> .env
      - name: Install Dependencies
        run: npm install --force
      - name: Build Nest App
        run: npm run build
        env:
          CI: false
      - name: Run test
        run: npm run test:e2e
      - name: Zip Dist Folder
        run: zip -r dist.zip ./dist
      - name: Zip node Modules
        run: zip -r node.zip node_modules
      - name: Copy Build files to the server
        run: |
          mkdir -p /home/runner/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/RealDeal1112023.pem
          chmod 700 /home/runner/.ssh
          chmod 600 /home/runner/.ssh/RealDeal1112023.pem
          scp -Tv -i /home/runner/.ssh/RealDeal1112023.pem -o StrictHostKeyChecking=no dist.zip node.zip package-lock.json package.json $SERVER_USER@$SERVER_IP:/tmp/be/
        shell: bash
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  CD:
    runs-on: ubuntu-latest
    needs: CI
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install npm
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 18
          nvm use 18
      - name: install PM2
        run: npm install pm2 --location=global
      - name: Deploy to Server
        run: |
          mkdir -p /home/runner/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/RealDeal1112023.pem
          chmod 700 /home/runner/.ssh
          chmod 600 /home/runner/.ssh/RealDeal1112023.pem
          SERVER_PATH=/root/
          chmod +x ./.github/workflows/nest.sh
          ssh -Tv -i /home/runner/.ssh/RealDeal1112023.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'bash -s' < ./.github/workflows/nest.sh
        shell: bash
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
